#!/usr/bin/bash
echo corriendo yacc...
bison -d parser.y -Wcounterexamples
echo corriendo lex...
flex lexer.l
echo compilando...
cc parser.tab.c lex.yy.c lib/expr.c -o programa
echo corriendo el programa...
./programa
